### ISSUE TITLE
karaoke version

### ISSUE THREAD

**Issue by Juna-Idler** [Juna-Idler/LyricsTTE_Spectro#5]
From YouTube Comment
> Are you planning on making a karaoke version as well?

I thought you would say that.
I just fit the drawing part (and others), but I'd like to experiment here a little more.

まあ言うと思ってた。
描画部分（とその他）をはめ込むだけだが、もうちょっとここで実験しておきたいかな。

**Comment by PlaylistsTrance** [comment]
Thank you, I'm looking forward to it. I made 6 LRC files yesterday with LyricsTTE_Spectro, most productive syncing day I've had so far. I've always wanted to have better visual feedback on my timings, and this is perfect for that.

**Comment by Juna-Idler** [comment]
https://github.com/Juna-Idler/RhythmiKaRuTTE_Spectro
