### ISSUE TITLE
TimeTune playback ignores volume slider

### ISSUE THREAD

**Issue by PlaylistsTrance** [Juna-Idler/LyricsTTE_Spectro#8]
Normally I play the song on full volume, but this time I lowered it with the volume slider from the player. However, when test-playing a timestamp in TimeTune, it used full volume. Would it be possible for it to use the volume level the user has set?

**Comment by Juna-Idler** [comment]
"the volume slider from the player"
I thought for a moment, but is this?(Google Chrome)
![2021-12-23 (4)](https://user-images.githubusercontent.com/78989193/147208292-f7720e4f-d883-4ece-abf9-ac5a48db1a6a.png)

Only in TimeTune mode, the Web Audio API is used to manipulate the raw audio data, so It will be a separate system from the audio tag player. Rate (playback speed) also has no effect.
The simplest, raw data is just connected to the output, so the current volume cannot be changed.
It is possible to add functions, but is it absolutely necessary?


TimeTuneモードの時のみWeb Audio APIを使って生の音声データを操作するので、
audioタグのプレイヤーとは別系統になります。Rate（再生速度）も影響しません。
最も単純な、生データを出力に繋げるているだけなので現状ボリュームの変更はできません。
機能追加自体は可能ですが、どうしても必要ですか？

**Comment by PlaylistsTrance** [comment]
No, it's not that important. I wasn't sure if it was possible to apply the main volume to TimeTune. Good to know that it would require separate volume control to be able to do that.
