### ISSUE TITLE
Red time line

### ISSUE THREAD

**Issue by PlaylistsTrance** [Juna-Idler/LyricsTTE_Spectro#9]
I think it would be a good idea if the vertical Tag Stamp time line was red (or any bright color that is clearly visible on the white spectrogram), just like the markers in Time Tune, for better visibility.

**Comment by Juna-Idler** [comment]
It's green in my personal image, but I don't know if it's good for visibility.
I wish I could set the color scheme of the display screen, but
I have to make a setting UI.

個人的なイメージでは緑だけど、視認性的に良いかは分からない。
表示画面の配色を設定できればいいんだけど、
設定用UIを作らないといけない。

**Comment by PlaylistsTrance** [comment]
Thank you, it's more visible now.
